# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmoduleschema < Formula
  desc "Return the variables, outputs, required providers, available versions, and submodules for any Terraform module in the OpenTofu or HashiCorp Terraform module registries."
  homepage "https://github.com/matt-FFFFFF/tfmoduleschema"
  version "0.3.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-FFFFFF/tfmoduleschema/releases/download/v0.3.0/tfmoduleschema_0.3.0_darwin_amd64.tar.gz"
      sha256 "a5eec2f05d74b7b2d50df1ed77dd5cdcbafc7a0fbcea46b9d2d782450c0d67a0"

      define_method(:install) do
        bin.install "tfmoduleschema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-FFFFFF/tfmoduleschema/releases/download/v0.3.0/tfmoduleschema_0.3.0_darwin_arm64.tar.gz"
      sha256 "61554af73954e82cb504ecb2cd0bcf5a7f8121571378c4f3ef8c33f5695c8e46"

      define_method(:install) do
        bin.install "tfmoduleschema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-FFFFFF/tfmoduleschema/releases/download/v0.3.0/tfmoduleschema_0.3.0_linux_amd64.tar.gz"
      sha256 "cd430043b06eb4aac9dca3a8d1b33538ed8ae99f2b744e1c79482a74d2f94f98"
      define_method(:install) do
        bin.install "tfmoduleschema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-FFFFFF/tfmoduleschema/releases/download/v0.3.0/tfmoduleschema_0.3.0_linux_arm64.tar.gz"
      sha256 "aca7d44a22ccd5e59253382758d53ec1fa231d9642231f23a7fa410da1e9f47f"
      define_method(:install) do
        bin.install "tfmoduleschema"
      end
    end
  end

  test do
    system "#{bin}/tfmoduleschema", "--version"
  end
end
