# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpluginschema < Formula
  desc "Download and retrieve schemas from Terraform/OpenTofu providers using the Terraform Plugin Protocol (v5 and v6)."
  homepage "https://github.com/matt-FFFFFF/tfpluginschema"
  version "0.10.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-FFFFFF/tfpluginschema/releases/download/v0.10.0/tfpluginschema_0.10.0_darwin_amd64.tar.gz"
      sha256 "a046796c33a74f432f83420cd187f28c50394c7e982e1f63997da7bc64875ef7"

      define_method(:install) do
        bin.install "tfpluginschema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-FFFFFF/tfpluginschema/releases/download/v0.10.0/tfpluginschema_0.10.0_darwin_arm64.tar.gz"
      sha256 "650929009d05fd82a4d0c83894ad91f7499813f5559cb2d328467558769a6c59"

      define_method(:install) do
        bin.install "tfpluginschema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-FFFFFF/tfpluginschema/releases/download/v0.10.0/tfpluginschema_0.10.0_linux_amd64.tar.gz"
      sha256 "effd0ed51b864baa1b8901c2104f8fe8e5a4062643d9438de4acff49170ceeef"
      define_method(:install) do
        bin.install "tfpluginschema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-FFFFFF/tfpluginschema/releases/download/v0.10.0/tfpluginschema_0.10.0_linux_arm64.tar.gz"
      sha256 "75b24a590187b0b2fe428b77362b428a17d869ccd08652d40b4836724b820183"
      define_method(:install) do
        bin.install "tfpluginschema"
      end
    end
  end

  test do
    system "#{bin}/tfpluginschema", "--version"
  end
end
